server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: airflow_logs
          __path__: /opt/airflow/logs/dag_id*/run_id*/task_id*/*.log
  - job_name: spark-master-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spark-master-logs
          __path__: /opt/airflow/logs/spark-master/*.log
